name: Mu4e Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: recipe
    attributes:
      label: How to reproduce?
      description: Tell us how to reproduce bug step by step?
      placeholder: Detailed steps to reproduce the behavior. If this is about a specific (kind of) message, **always** attach an (anonymized as need) example message.
    validations:
      required: true
  - type: dropdown
    id: Emacs-version
    attributes:
      label: Emacs Version
      description: What version of Emacs are you running?
      options:
        - Emacs-25*
        - Emacs-26*
        - Emacs-26.3
        - Emacs-27.1
        - Emacs-27.2
        - Emacs-28.0.50
    validations:
      required: true
  - type: dropdown
    id: Platform
    attributes:
      label: OS
      description: What OS are you running on?
      options:
        - GNU/Linux
        - Freebsd
        - MacOSX
        - Windows
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Minimal configuration
      description: you are running vanilla emacs (i.e. without Doom, Evil, Spacemacs etc.) (otherwise, please try to reproduce without those.
      options:
        - label: I agree using a minimal configuration 
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Minimal configuration
      description: you are running mu4e without any third-party extensions (otherwise, please try to reproduce without those).
      options:
        - label: I agree not using third party extensions
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Minimal configuration
      description: you are running either the latest 1.6.x release, or a 1.7.x development release (otherwise, please upgrade).
      options:
        - label: I agree not using third party extensions
          required: true
